version: "3.7"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-db:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '9000:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - 'db:pgsql-server'

volumes:
  postgres-db:
  pgadmin-data: