DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS groups CASCADE;

DROP TABLE IF EXISTS account_to_group CASCADE;

DROP TABLE IF EXISTS payment CASCADE;

DROP TABLE IF EXISTS payment_configuration CASCADE;

COMMIT;